Add cache item TTL
evaera/RoVer pull request #325
Opened 2021-03-21 18:04 UTC by Wolftallemo

Allow setting a custom TTL for each collection instead of clearing everything every 30 seconds. `Cache.set` now takes an expiry parameter, which will be checked by the autoclear every 60 seconds. Setting the expiry to 0 will preserve the old behavior of it being cleared on every autoclear.

2021-03-22 17:24 UTC, evaera requested changes

2021-03-22 17:24 UTC, evaera commented on src/DiscordMember.js
> +        await Cache.set('users', this.id, data, false)
You shouldn't have to specify the TTL for set calls. Instead, let us specify a TTL in the `Cache` per-collection. Not per-key.

You should leave everything else the same, just have a constant object at the top of the file with a list of collections to not clear. Clear any collection not in that object the standard way.

2021-03-22 17:24 UTC, evaera commented on src/GlobalCache.js
> +      Object.keys(this.collections).forEach(col => { if (this.collections[col].expiry <= Date.now() || !this.collections[col]['expiry']) this.collections[col] = {} })
Please do not write code like this all on one line

2021-03-22 22:15 UTC, evaera requested changes

2021-03-22 22:15 UTC, evaera commented on src/GlobalCache.js
> +  set (collection, key, value, expiry) {
Remove extra param

2021-03-22 22:15 UTC, evaera commented on src/GlobalCache.js
> +    return cacheTTLs[abbrevName]
What about a default TTL?

2021-03-22 22:15 UTC, evaera commented on src/GlobalCache.js
> +        if (this.collections[col]['created'] + ttl <= Date.now()) delete this.collections[col]
Put this on its own line and wrap in curly braces

2021-03-22 22:15 UTC, evaera commented on src/GlobalCache.js
> +const cacheTTLs = { blacklists: Infinity, bindings: 120000, groups: 360000, users: 45000 }
Break out each onto their own lines

2021-03-23 19:32 UTC, evaera submitted a review, later dismissed

2021-03-23 19:32 UTC, evaera commented on src/GlobalCache.js
> +    if (!collection['created']) collection['created'] = Date.now()
```suggestion
    if (!collection.created) collection.created = Date.now()
```

2021-03-23 19:32 UTC, evaera commented on src/GlobalCache.js
> +        if (this.collections[col]['created'] + ttl <= Date.now()) {
```suggestion
        if (this.collections[col].created + ttl <= Date.now()) {
```

2021-03-23 19:47 UTC, evaera commented
Does this work? Can you test it? @Wolftallemo

2021-03-23 20:05 UTC, Wolftallemo commented
From my own testing it appears to work, although some things aren't set in cache even though they probably should be (but that's for another pr)

2021-03-26 23:38 UTC, Rythian2277 commented
I've began testing with this functionality on a bot in multiple servers, I should have reliable results within a day or two.

2021-03-29 10:44 UTC, Rythian2277 commented
No errors have come around from these changes over the past 3 days.

2021-04-04 11:40 UTC, Rythian2277 approved these changes

2021-04-06 18:40 UTC, Rythian2277 commented
@evaera There's no issues with this but due to it being an edit to caches, I would prefer it if you did the final review and merging.

2021-04-07 00:28 UTC, merged